//! Generated by `build.rs` via `risc0_build::embed_methods`.
//!
//! Exposes, for the `guest` program:
//! * `GUEST_ELF` — the zkVM ELF bytes, to hand to the prover
//! * `GUEST_ID`  — the image id (digest of the ELF), the guest's identity
//! * `GUEST_PATH` — path to the built ELF on disk
include!(concat!(env!("OUT_DIR"), "/methods.rs"));
